name: commit to github

# on:
#   workflow_dispatch

# Triggers the workflow on api call
on:
  repository_dispatch:
    types: [instance]
    
env:
  namePrefix: "${{ github.event.client_payload.namePrefix }}"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Job1:
    name: update files
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Display value
       run: |
        echo $namePrefix
        echo namePrefix

  Job2:
    needs: Job1
    name: Send call to newworkflow workflow
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Repository Dispatch to subdomain workflow
       uses: peter-evans/repository-dispatch@v1
       with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          event-type: subdomain
          client-payload: '{"data": "hello"}'  
